version: 2

models:
  - name: stg_facebook_ads_campaigns
    description: "Facebook Ads Ads"
    columns:
      - name: ad_campaign_id
        tests:
          - unique
          - not_null
          - dbt_utils.not_constant
      - name: ad_campaign_name
        tests:
          - unique
          - not_null
          - dbt_utils.not_constant
      - name: ad_campaign_status
        tests:
          - unique
          - not_null
  - name: stg_facebook_ads_ad_groups
    description: "Facebook Ads Ad Groups"
    columns:
      - name: ad_group_id
        tests:
          - unique
          - not_null
          - dbt_utils.not_constant
      - name: ad_group_name
        tests:
          - unique
          - not_null
          - dbt_utils.not_constant
      - name: ad_campaign_id
        tests:
          - unique
          - not_null
          - dbt_utils.not_constant
          - relationships:
              to: ref('stg_facebook_ads_campaigns')
              field: ad_campaign_id
              severity: warn
  - name: stg_facebook_ads
    description: "Facebook Ads Ads"
    columns:
      - name: ad_id
        tests:
          - unique
          - not_null
      - name: ad_status
        tests:
          - not_null
      - name: ad_type
        tests:
          - not_null
      - name: ad_group_id
        tests:
          - unique
          - not_null
          - dbt_utils.not_constant
          - relationships:
              to: ref('stg_facebook_ads_ad_groups')
              field: ad_group_id
              severity: warn
