version: 2

sources:

  - name: segment_google_ads
    database: "{{ var('stg_google_ads_segment_database') }}"
    schema: "{{ var('stg_google_ads_segment_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: uuid_ts

    tables:
      - name: campaign_performance_reports
      - name: campaigns
      - name: ad_performance_reports
      - name: ad_groups
      - name: ads
