version: 2
models:
  - name: wh_companies_dim
    description: "Companies Dimension"
    columns:
      - name: company_pk
        tests:
          - unique
          - not_null
      - name: company_name
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
  - name: wh_contacts_dim
    description: "Contacts Dimension"
    columns:
      - name: contact_pk
        tests:
          - unique
          - not_null
      - name: contact_name
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
